version: '3'

services:
  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # cube:
  #   image: cubejs/cube:latest
  #   ports:
  #     - 4000:4000
  #   environment:
  #     - CUBEJS_DEV_MODE=true
  #   volumes:
  #     - ./cube/conf:/cube/conf
  #   depends_on:
  #     - postgres
