version: '3'

services:
  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
