- module: covid19data
  cfg:
    sink:
      type: csv
      name: ingestion/data/covid_au_data
      chunksize: 100
      mode: replace
    source:
      filename: COVID_AU_state.csv
- module: covid19data
  cfg:
    sink:
      type: csv
      name: ingestion/data/covid_au_death_data
      chunksize: 100
      mode: replace
    source:
      filename: COVID_AU_deaths.csv
- module: vaccinations
  cfg:
    sink:
      type: csv
      name: ingestion/data/covid_au_vaccination_data
      chunksize: 100
      mode: replace
    source:
      collection: covid-19-vaccination-vaccination-data
- module: vaccinations
  cfg:
    sink:
      type: csv
      name: ingestion/data/covid_vaccination_by_lga
      chunksize: 100
      mode: replace
    source:
      collection: covid-19-vaccination-geographic-vaccination-rates-lga
- module: nsw_government
  cfg:
    sink:
      type: csv
      name: ingestion/data/covid_nsw_tests_by_location
      chunksize: 100
      mode: replace
    source:
      resource_type: tests_by_location
- module: nsw_government
  cfg:
    sink:
      type: csv
      name: ingestion/data/covid_nsw_cases_by_location
      chunksize: 100
      mode: replace
    source:
      resource_type: cases_by_location
